### ISSUE TITLE
Accessibility: check that image tags have alt attributes

### ISSUE THREAD

**Issue by pdpinch** [mitodl/openedx-course-test#11]
... and that they're not empty

**Comment by pdpinch** [comment]
since this is accessibility 101, it might be more effective to look for a package that will check all HTML in the course for this basic stuff. I just don't know how hard it might be to adapt the package to OLX structures.

**Comment by pwilkins** [comment]
Everyone probably already knows this, but once we move into the realm of accessibility, we have experienced resources that can help.  I'm thinking of Mary Ziegler in the ATIC lab and the new accessibility lead at edX.

**Comment by pdpinch** [comment]
Thanks. Issue #10 arrived via Mary Ziegler's team at ATIC. In my experience they haven't been very optimistic about automated testing, but I think we will eventually be able to use it to offload the basic accessibility issues onto course authoring teams -- so we all can focus on the interesting stuff. 

Expect more issues over time.

**Comment by carsongee** [comment]
Same as 10, should this be a warn or a fail?
